import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

const TOOLS = [
  "/subnet-calculator",
  "/cidr-calculator",
  "/vlsm-calculator",
  "/subnet-splitter",
  "/subnet-range-calculator",
  "/usable-host-calculator",
  "/subnet-mask-calculator",
  "/wildcard-mask-calculator",
  "/cidr-to-subnet-mask",
  "/subnet-mask-to-cidr",
  "/network-address-calculator",
  "/broadcast-address-calculator",
  "/ipv4-validator",
  "/ipv4-to-binary",
  "/binary-to-ipv4",
  "/ip-range-calculator",
  "/ip-range-generator",
  "/private-ip-checker",
  "/ipv6-subnet-calculator",
  "/ipv6-validator",
  "/ipv6-compression",
  "/port-number-lookup",
  "/http-status-code-lookup",
  "/dns-lookup",
  "/reverse-dns-lookup",
  "/mx-record-lookup",
  "/a-record-lookup",
  "/cname-lookup",
  "/txt-record-lookup",
  "/ns-record-lookup",
  "/ping-tester",
  "/traceroute",
  "/http-header-checker",
  "/url-parser",
  "/url-encoder-decoder",
  "/hex-to-binary",
  "/binary-to-hex",
  "/decimal-to-binary",
  "/binary-to-decimal",
  "/hex-to-decimal",
  "/decimal-to-hex",
  "/mac-address-formatter",
  "/mac-address-validator",
  "/dns-propagation-checker",
  "/ip-geolocation-lookup",
  "/asn-lookup",
  "/bgp-prefix-lookup",
  "/whois-lookup",
  "/ipv4-header-decoder",
  "/tcp-header-decoder",
  "/udp-header-decoder",
  "/icmp-type-code-lookup",
  "/ethernet-frame-decoder",
  "/bandwidth-calculator",
  "/throughput-calculator",
  "/latency-calculator",
  "/transfer-time-calculator",
  "/mtu-calculator",
  "/mss-calculator",
  "/tcp-window-size-calculator",
  "/cisco-wildcard-mask-calculator",
  "/cisco-acl-generator",
  "/cisco-vlan-calculator",
  "/cisco-subnet-calculator",
  "/cisco-port-range-generator",
  "/cisco-ip-calculator",
  "/cisco-config-generator",
  "/ospf-cost-calculator",
  "/eigrp-metric-calculator",
  "/stp-root-bridge-calculator",
  "/subnetting-practice",
  "/ip-address-quiz",
  "/cidr-practice",
  "/vlsm-practice",
  "/wildcard-mask-practice",
  "/port-number-quiz",
  "/osi-model-reference",
  "/tcp-ip-model-reference",
  "/tcp-flags-reference",
  "/dns-record-types-reference",
  "/ipv4-address-classes-reference",
  "/ipv6-prefix-reference",
  "/http-status-codes-reference",
  "/well-known-ports-reference",
  "/network-protocol-reference",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = SITE_URL;
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    ...TOOLS.map((p) => ({
      url: base + p,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
  ];
}
